### ISSUE TITLE
Update screenshots to be distro-agnostic

### ISSUE THREAD

**Issue by tsimonq2** [snapcraft-gui/snapcraft-gui#12]
Use `shutter` or another tool to get a screenshot of **just** the window and some plain window borders. This would make it look a lot cleaner.

For example, I've seen LibreOffice use Lubuntu for screenshots. Lubuntu has a simple window border and it doesn't get in the way.

**Comment by keshavbhatt** [comment]
nice idea , will update screenshots soon.
okay :+1:

**Comment by keshavbhatt** [comment]
Updated some , will update the rest as the changes will happen to GUI of specific part of the application.
