### ISSUE TITLE
The menu items are big compared to the menu text

### ISSUE THREAD

**Issue by tsimonq2** [snapcraft-gui/snapcraft-gui#16]
If you look at this screenshot, something is obviously wrong:
![wrong-menu](http://i.imgur.com/0rIaxsE.png)
The menu text is small but the menu item is big.

**Comment by keshavbhatt** [comment]
Thanks , will fix this asap. ,  this think can be noticed here on ubuntu with unity D.E so i never got my eye on that :+1:

**Comment by keshavbhatt** [comment]
That's D.E related styling of menu , Menu and Menu items are set to have same font size see in style.qss in source .
