### ISSUE TITLE
Snap Package Manager claims I don't have network access

### ISSUE THREAD

**Issue by tsimonq2** [snapcraft-gui/snapcraft-gui#17]
If you look at this screenshot:

![bad-bad-snap-package-manager](http://i.imgur.com/YxaFaz8.png)

It claims I don't have network access when I really do. No terminal output or anything (helpful when wanting to debug something, you can launch it from the terminal).

**Comment by keshavbhatt** [comment]
i will fix this , still some work is needed to be done on update manager there.
Thanks for the reminder..

**Comment by keshavbhatt** [comment]
it wont do this now :100:
