### ISSUE TITLE
I shouldn't be able to select the `Select a .snap package` with my cursor

### ISSUE THREAD

**Issue by tsimonq2** [snapcraft-gui/snapcraft-gui#19]
While I can't type in the box, I can select the box and it will still show a blue border:

![bad-box](http://i.imgur.com/eFSEiBX.png)

I shouldn't be able to do that.

**Comment by keshavbhatt** [comment]
that's a readonly textedit , and "Select a .snap package" is placeholder text how you are able to select that text ?? :P

**Comment by tsimonq2** [comment]
@keshavbhatt I can't edit the text, it's just highlighted like that when I click it.

**Comment by keshavbhatt** [comment]
there is nothing to select in  there actually , user have to click the select button beside the line edit and choose the snap from dialog and then if he select a package line edit will show the path .

**Comment by keshavbhatt** [comment]
works fine as expected.
