### ISSUE TITLE
Package it into snap

### ISSUE THREAD

**Issue by FaraoneLele** [snapcraft-gui/snapcraft-gui#20]
Why not package snapcraft-GUI into a snap?

**Comment by tsimonq2** [comment]
This is already done. :) 

@FaraoneLele could you close this?

**Comment by FaraoneLele** [comment]
How I can install it as a Snap?

**Comment by keshavbhatt** [comment]
this is not done yet , snap is right now not possible due to this reason -
 1- there is no interface in snap yet which allow talk to snapd installed on user's system.

**Comment by tsimonq2** [comment]
Oh sorry, I assumed it was good to go because I saw a snapcraft.yaml.
@keshavbhatt do you plan on fixing this then?

**Comment by FaraoneLele** [comment]
@keshavbhatt maybe can you open a bug on Snapd launchpad page for support the interface

**Comment by keshavbhatt** [comment]
@tsimonq2 as @FaraoneLele  said we have to wait until they provide such access via interface to make data transactions with user's installed (or system's) snapd.

**Comment by tomascw** [comment]
Now it's truly done!

**Comment by keshavbhatt** [comment]
thanks :) but it can't perform package management since it need to talk with snapd and snap , which is offered by snapcraft-GUI

**Comment by keshavbhatt** [comment]
we have snapcraft.yaml now which snaps the code and turn it into snap package . the limitations we having are not related to our work, things will change as the snap and snapd will develop in future.

**Comment by keshavbhatt** [comment]
we will not choose snap package as the default mean of distribution of the application as it makes lots of parts of the application not work properly as we want. 
this is due to snap again.
