### ISSUE TITLE
Write contribution guide to help new contributors write code

### ISSUE THREAD

**Issue by tsimonq2** [snapcraft-gui/snapcraft-gui#9]
You should write a contributor guide, stating the following:
 - What it's written in and links to tutorials for learning that language.
 - How you would prefer people contribute code (style guides, whatever matches what you like)
 - Basic Git tutorial (not everyone knows how to use Git :P).
 - Example.
 - Any other notes you might have for contributors.

**Comment by keshavbhatt** [comment]
ty , all coming soon tonight .

**Comment by keshavbhatt** [comment]
Done .
